NUMBER_OF_BOXES = 1

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  (2..(NUMBER_OF_BOXES + 1)).each do |i|

    config.vm.define "Ubuntu#{i}".to_sym do |ubuntu|
      ubuntu.vm.hostname = "Ubuntu#{i}"
      ubuntu.vm.network :private_network, ip: "172.16.1.#{i}", :netmask => "255.255.0.0"

      ubuntu.vm.provision :shell, path: "../PuppetClient.sh"
      ubuntu.vm.provision :shell, inline: 'cp /vagrant/common.hosts /etc/hosts'

      ubuntu.vm.synced_folder "../", "/vagrant/"

    end

  end
end
