Vagrant.configure("2") do |config|

  config.vm.define "PuppetMaster" do |master|
    master.vm.box = "Puppetlabs Ubuntu 12.04.2 x86_64, VBox 4.2.10"
    master.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
    master.vm.hostname = "master"
    master.vm.synced_folder "../", "/etc/puppet"
    master.vm.network :private_network, ip: "172.16.0.2", :netmask => "255.255.0.0"

    master.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
    end

    master.vm.provision :shell, path: "./PuppetMaster.sh"
    master.vm.provision :shell, inline: 'cp /vagrant/common.hosts /etc/hosts'
  end
end
