Vagrant.configure("2") do |config|

  config.vm.define "PuppetMaster" do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.hostname = "master"
    master.vm.synced_folder "../", "/etc/puppet"
    master.vm.network :private_network, ip: "172.16.0.2", :netmask => "255.255.0.0"

    master.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
    end

    master.vm.provision :shell, path: "./PuppetMaster.sh"
    master.vm.provision :shell, path: "./PuppetDB.sh"
    master.vm.provision :shell, inline: 'cp /vagrant/common.hosts /etc/hosts'
  end
end
